TreeNode searchBST(TreeNode root, int val)
TreeNode insertIntoBST(TreeNode root, int val)
TreeNode deleteNode(TreeNode root, int key)
boolean isValidBST(TreeNode root)
TreeNode sortedArrayToBST(int[] nums)
void printTree(TreeNode root)  